import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Paths
GEN_CSV = "building_params.csv"  # generated by extract_distributions_dataset.py (now normalized to SI in save_csv_json)
RANGE_CSV = os.path.join("resstock_range", "options_saturations_summary.csv")
OUT_DIR = "realism_figures"

os.makedirs(OUT_DIR, exist_ok=True)


# (name, gen_col, summary_metric, xlabel)
VARIABLES = [
    ("R_wall",   "R_wall",   "R_wall_SI",      "Wall R-value (m²·K/W)"),
    ("R_roof",   "R_roof",   "R_roof_SI",      "Roof/Attic R-value (m²·K/W)"),
    ("COP_cool", "COP_cool", "COP_cool",       "Cooling efficiency (COP)"),
    ("COP_heat", "COP_heat", "COP_heat_like",  "Heating efficiency (–)")
]


def load_data():
    if not os.path.exists(GEN_CSV):
        raise FileNotFoundError(f"Generated dataset not found: {GEN_CSV}")
    if not os.path.exists(RANGE_CSV):
        raise FileNotFoundError(f"ResStock summary not found: {RANGE_CSV}")
    gen = pd.read_csv(GEN_CSV)
    ranges = pd.read_csv(RANGE_CSV)
    return gen, ranges


def ecdf(x: np.ndarray):
    x = np.sort(x)
    n = len(x)
    y = np.arange(1, n + 1) / n
    return x, y


def get_range(summary_df: pd.DataFrame, metric: str):
    sub = summary_df[summary_df["metric"] == metric]
    if sub.empty:
        return None
    row = sub.iloc[0]
    # Some summaries might be missing q10/q90; handle robustly
    q10 = float(row.get("q10", np.nan))
    q50 = float(row.get("q50", np.nan))
    q90 = float(row.get("q90", np.nan))
    return q10, q50, q90


def plot_one(name: str,
             gen_vals: np.ndarray,
             q10: float,
             q50: float,
             q90: float,
             xlabel: str,
             out_path: str):
    if gen_vals.size == 0:
        print(f"[skip] {name}: no generated data.")
        return

    x, y = ecdf(gen_vals)

    plt.figure(figsize=(6, 4))

    # Generated ECDF
    plt.plot(x, y, linewidth=2, label="Generated homes")

    # ResStock 10–90% band
    if not np.isnan(q10) and not np.isnan(q90) and q10 < q90:
        plt.axvspan(q10, q90, alpha=0.15, label="ResStock 10–90%")

    # ResStock median
    if not np.isnan(q50):
        plt.axvline(q50, linestyle="--", linewidth=1.5, label="ResStock median")

    # Coverage metric: % of generated samples within [q10, q90]
    coverage = np.nan
    if not np.isnan(q10) and not np.isnan(q90) and q10 < q90:
        coverage = ((gen_vals >= q10) & (gen_vals <= q90)).mean() * 100.0

    title = f"{name} realism"
    if not np.isnan(coverage):
        title += f" (coverage: {coverage:.1f}% in 10–90%)"

    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel("ECDF")
    plt.grid(alpha=0.2)
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.savefig(out_path, dpi=300)
    plt.close()

    if not np.isnan(coverage):
        print(f"[ok] {name}: saved {out_path} (coverage {coverage:.1f}% in 10–90%)")
    else:
        print(f"[ok] {name}: saved {out_path} (no valid 10–90% band; plotted ECDF only)")


def main():
    gen, ranges = load_data()

    for name, gen_col, metric, xlabel in VARIABLES:
        if gen_col not in gen.columns:
            print(f"[skip] {name}: generated column '{gen_col}' not found in {GEN_CSV}")
            continue

        rng = get_range(ranges, metric)
        if rng is None:
            print(f"[skip] {name}: metric '{metric}' not found in {RANGE_CSV}")
            continue

        q10, q50, q90 = rng

        vals = (
            gen[gen_col]
            .astype(float)
            .replace([np.inf, -np.inf], np.nan)
            .dropna()
            .values
        )

        if vals.size == 0:
            print(f"[skip] {name}: all values NaN/invalid after cleaning.")
            continue

        out_path = os.path.join(OUT_DIR, f"ecdf_{name}.png")
        plot_one(name, vals, q10, q50, q90, xlabel, out_path)


if __name__ == "__main__":
    main()
